### ISSUE TITLE
[Android] Badge and Notification is not resetted after open App via AppIcon

### ISSUE THREAD

**Issue by Hunv** [OneSignal/OneSignal-Xamarin-SDK#103]
**Description:**
If you are using Android 8 and above, which has the blue badge-dots next to the app icon on new messages, the badges and also notifications are not resetted if you start the App via the icon on the start screen. 

**Environment**
I am running version 3.2.0 but this also happens on 3.1.1 via Nuget.
I'm using a Pixel 2 with Android 8.1.

**Steps to Reproduce Issue:**
1. Push a Message to via Dashboard
2. You see a new Notification for the App in the Actionbar and the Badge
3. Open the app via app icon (not via actionbar)
4. Notification and Badge are still existing (should not be)
5. switch back to start screen
6. open actionbar and select the notification
7. App will open and notification and the badge are gone (what I want)

**Comment by jkasten2** [comment]
@Hunv For Android apps this expected behavior. Notifications are normally only cleared by the user from notification shade when they swipe them away or just the single notification they tapped on.

If you do want to enforce always clearing notifications when your app is open then you can call [`OneSignal.clearOneSignalNotifications()`](https://documentation.onesignal.com/docs/android-native-sdk#section--clearonesignalnotifications-) when your app is resumed or started.

Notification dot on Android apps will show if there are any notifications in the shade for your app and they are currently enabled for the notification category / channel.
