### ISSUE TITLE
Android dependecies upper version restriction? 

### ISSUE THREAD

**Issue by EmilAlipiev** [OneSignal/OneSignal-Xamarin-SDK#105]
why are you having version restriction on dependency xamarin android packages? I would like to use higher available version of support packages. for example, there customtabs version 27.2.1 version but because of your 27.2.0, it is not possible. whats the purpose of it?

![image](https://user-images.githubusercontent.com/10422347/41509110-48046d18-724f-11e8-8f06-e8bf41e52674.png)

**Comment by jkasten2** [comment]
@EmilAlipiev We restrict dependencies to the newest version at the time we tested. This is to ensure a newer untested version is not used automatically which could create issues.

The current latest version of [CustomTabs is 27.0.2.1](https://www.nuget.org/packages/Xamarin.Android.Support.CustomTabs/) which should be included in `< 27.2.0` defined in the nuget spect.

I did add the OneSignal SDK 3.2.0 to a new project and it did pull in `27.0.2` instead of the newest by default. This might be an issue due to Xamarin changing the version from a 3 part number to 4 part. However you can right click on the library under packages and still update it to the latest without any issues.

**Comment by EmilAlipiev** [comment]
hi, now there is support libraries 28 and i would like to use it. because of OneSignal library it is not possible. can we update nuget with 28 version?

**Comment by ArgusMagnus** [comment]
This is an issue for me as well

**Comment by jkasten2** [comment]
Sorry for the delay, we just released a 3.3.0-beta version with updated dependencies.
https://www.nuget.org/packages/Com.OneSignal/3.3.0-beta

Please try it out and let us know if it resolves this issue with MonoAndroid 9.0 compatibility. Thanks.

**Comment by rgomezp** [comment]
Closing due to no response
