### ISSUE TITLE
Is there a big difference between 3.0.1 and 3.2.0?

### ISSUE THREAD

**Issue by EmilAlipiev** [OneSignal/OneSignal-Xamarin-SDK#107]
HI,

since I upgraded my project to 3.1 and 3.2.0, i am having several problems on android. especially problem with the debug symbols on release mode. it looks like it wont even be fixed soon. 
When I see the release notes, there are a lot of changes and support library dependencies added. So my question is is it safe to use 3.0.1 version? it looks like that GDPR is also important part of it.
Thank you for your help

**Comment by Nightsd01** [comment]
@EmilAlipiev I would suspect that the problems you are seeing in Android would be configuration/dependency issues with your project, I wouldn't automatically assume they are issues with the SDK.

Can you post some details on the issues you are running into with 3.2.0? Yes - to answer your question, we have fixed a lot of bugs since 3.0.1, and added features like GDPR compliance and email and more.

**Comment by EmilAlipiev** [comment]
well, i havent changed my android settings since a year or more and all other onesignal versions are working fine but starting from 3.1, i am seeing this warning and even it returns error when i am trying to archive an apk https://github.com/OneSignal/OneSignal-Xamarin-SDK/issues/79
If i downgrade to 3.0.1, all works fine no more this error. Ok, I recognized one thing that 3.0.1 is not working android 8 versions, thats why also not usable.
