### ISSUE TITLE
Media Attachaments on Adroid

### ISSUE THREAD

**Issue by elyfran** [OneSignal/OneSignal-Xamarin-SDK#108]
Is possible to send media attachments (.avi) to Android or only works to iOS?

**Comment by jkasten2** [comment]
@elyfran .avi or other video files are not supported as attachments on notifications on Android. Animated gifs also do not play, they will just be a static image. This is a limitation of Android itself rather than this SDK.

For iOS these are supported on 10+ and are played when you 3d touch the notification.
