### ISSUE TITLE
Amazon Fire requires Google play services?

### ISSUE THREAD

**Issue by EmilAlipiev** [OneSignal/OneSignal-Xamarin-SDK#109]
how does one signal works on amazon devices? It looks like that it requires google play services? so how are we supposed to use one signal on amazon fire devices?

![image](https://user-images.githubusercontent.com/10422347/43025014-72381004-8c70-11e8-9b4e-9253423f9b5c.png)

I followed the steps here but still nothing changes. So the question is can we not use onesignal on xamarin projects for Amazon? 
https://documentation.onesignal.com/docs/amazon-sdk-setup

**Comment by EmilAlipiev** [comment]
after uninstalling app and reinstalling message changed as 

![image](https://user-images.githubusercontent.com/10422347/43028089-10f0a9a6-8c7e-11e8-856d-91b294d83f8c.png)

**Comment by jkasten2** [comment]
@EmilAlipiev OneSignal does work with FireOS devices and uses Amazon's ADM messaging service instead of FCM / GCM. Make sure you have all the entires located in this guide.
https://documentation.onesignal.com/docs/unity-sdk-setup#section-4-amazon-adm-setup

If your missing the following from your `AndroidManifest.xml` then the Android SDK will try to fallback to GCM / FCM as ADM will not be available for your app.
```xml
<application>
  <amazon:enable-feature android:name="com.amazon.device.messaging" android:required="false"/>
</application>
```

**Comment by EmilAlipiev** [comment]
Yes i have that line and i already followed every single step on tthat article. My Manifest looks the same but as i said it always return no push Token. I saw similar posts for cordova

**Comment by rgomezp** [comment]
Hello,
Sorry for the long delay. Are you still having issues?

**Comment by EmilAlipiev** [comment]
i think that it is resolved now. i am closing this issue.

**Comment by Shani-Rabi** [comment]
I an having the same problem.
How did you solve the issue?

**Comment by EmilAlipiev** [comment]
i dont see the problem simply using the latest version. what do you get?
