### ISSUE TITLE
Error while reading from SharedPreferences MODE_WORLD_READABLE no longer supported

### ISSUE THREAD

**Issue by matheusdelvalle** [OneSignal/OneSignal-Xamarin-SDK#135]
Hello.
I'm having a huge problem with One Signal SKD for Xamarin Forms.
My App do not receive Push Notifications when the Android Version is higher than 7.1.

The Apps give this Exception:

Error while reading from SharedPreferences

I already tried update the OneSignal version and all the Google packages too, but didint work.
Could you help me please? I'm having a big problem with my clients. 

Xamarin Forms Version: 2.5.0.122203
Xamarin.Android.Support: 28.0.0.1
OneSignal Version: 3.2.2

```
02-28 18:39:53.802 I/OneSignal(20308): Device registered, push token = APA91bFc1qGzUd1Afo
02-28 18:39:53.817 W/AdvertisingIdClient(20308): Error while reading from SharedPreferences 
02-28 18:39:53.817 W/AdvertisingIdClient(20308): java.lang.SecurityException: MODE_WORLD_READABLE no longer supported
02-28 18:39:53.817 W/AdvertisingIdClient(20308): at android.app.ContextImpl.checkMode(ContextImpl.java:2495)
02-28 18:39:53.817 W/AdvertisingIdClient(20308): at android.app.ContextImpl.getSharedPreferences(ContextImpl.java:414)
02-28 18:39:53.817 W/AdvertisingIdClient(20308): at android.app.ContextImpl.getSharedPreferences(ContextImpl.java:404)
02-28 18:39:53.817 W/AdvertisingIdClient(20308): at com.google.android.gms.ads.identifier.AdvertisingIdClient.getAdvertisingIdInfo(Unknown Source:12)
02-28 18:39:53.817 W/AdvertisingIdClient(20308): at com.onesignal.AdvertisingIdProviderGPS.getIdentifier(AdvertisingIdProviderGPS.java:45)
02-28 18:39:53.817 W/AdvertisingIdClient(20308): at com.onesignal.OneSignal.registerUserTask(OneSignal.java:1223)
02-28 18:39:53.817 W/AdvertisingIdClient(20308): at com.onesignal.OneSignal.access$2300(OneSignal.java:80)
02-28 18:39:53.817 W/AdvertisingIdClient(20308): at com.onesignal.OneSignal$7.run(OneSignal.java:1206)
02-28 18:39:53.817 W/AdvertisingIdClient(20308): at java.lang.Thread.run(Thread.java:764)

```

**Comment by rgomezp** [comment]
Hello,
Sorry for the delay here. In the future, feel free to reach out through our support channel on OneSignal.com for time-sensitive support inquiries. 

It's possible that the problem is that there are Android support library dependencies that are likely out of the version ranges we have in our plugin. To fix this, re-install the plugin but make sure to install the newest beta version where we have added support for the latest Android API. Make sure all your Android support library dependencies are also upgraded. Furthermore, make sure that the entire project is configured to use Android Pie. This includes the General build settings as well as Android Application settings.

<img width="961" alt="Screen Shot 2019-04-12 at 11 10 54 AM" src="https://user-images.githubusercontent.com/11739227/56057525-db81f600-5d13-11e9-8dac-5ec54a8213e6.png">

**Comment by rgomezp** [comment]
Closing due to no response

**Comment by ferrydeboer** [comment]
I had time to look into this. I tried the suggested above. But on at least my Oreo device this still issue is not resolved.

**Comment by rgomezp** [comment]
@ferrydeboer ,
Could you please provide more details regarding your environment?

**Comment by ferrydeboer** [comment]
The device I'm testing this on is a Nexus 5x running on Android 8.1.0. What else do you need to know?

**Comment by rgomezp** [comment]
I'm not convinced this is a OneSignal issue. Please tell me if you think otherwise. Although it appears in the trace, it looks like the error occurs later and is a system error `java.lang.SecurityException: MODE_WORLD_READABLE no longer supported` due to being deprecated. Learn more on this [here](https://developer.android.com/reference/android/content/Context.html#MODE_WORLD_READABLE).

**Comment by ferrydeboer** [comment]
From what I observed, manually installing GooglePlayservices.Gcm v60.x makes this message disappear.

**Comment by rgomezp** [comment]
@ferrydeboer ,
Thanks for figuring that out. Since I haven't heard back from OP, will be closing this issue. Please let me know if you would like to reopen with a @
