### ISSUE TITLE
PHONE_REGISTRATION_ERROR

### ISSUE THREAD

**Issue by srdmnc** [OneSignal/OneSignal-Xamarin-SDK#169]
**Description:**
Getting google play services error in the dashboard - might be due to this IOException.

**Environment**

1. v.3.5.0
2. nuget

**Steps to Reproduce Issue:**

 1. Add version 3.5.0 of the Xamarin SDK to your project
  2. Initialize the SDK with your App ID
  3. Attempt to receive a push notification

**Anything else:**

```
[OneSignal] Error Getting FCM Token
[OneSignal] java.io.IOException: PHONE_REGISTRATION_ERROR
[OneSignal] 	at com.google.firebase.iid.zzr.zza(Unknown Source:67)
[OneSignal] 	at com.google.firebase.iid.zzr.zza(Unknown Source:80)
[OneSignal] 	at com.google.firebase.iid.zzu.then(Unknown Source:4)
[OneSignal] 	at com.google.android.gms.tasks.zzd.run(Unknown Source:5)
[OneSignal] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
[OneSignal] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
[OneSignal] 	at java.lang.Thread.run(Thread.java:764)

[FirebaseInstanceId] Token retrieval failed: PHONE_REGISTRATION_ERROR
```

Platform: Xamarin Forms

**Comment by rgomezp** [comment]
Can you please include more details such as device make, model, OS & versions as well as full config/gradle files, logcats, and anything else that may help us reproduce/debug the issue? Thanks

**Comment by srdmnc** [comment]
Device: Redmi Note 6 Pro
OS: MIUI 10
The logcat error is [here](https://github.com/OneSignal/OneSignal-Xamarin-SDK/issues/169#issue-509803220)

**Comment by srdmnc** [comment]
@rgomezp Any update on this?

**Comment by jkasten2** [comment]
@srdmnc `PHONE_REGISTRATION_ERROR` is an error thrown by Firebase but I couldn't find any specifics other than the "Google Play services" app on the device is having an issue.

I recommend making sure you can log into the Google Play store on the device and can download an app to make sure the device can fully authenticate with Google.

Since the issue is device related I recommend trying a different device the Android Studio emulator if this issue is blocking your development.

**Comment by rgomezp** [comment]
Closing due to no response
