### ISSUE TITLE
OneSignal.Default.SetExternalUserId  value cannot be null  - Parameter name hashtoken

### ISSUE THREAD

**Issue by developer9969** [OneSignal/OneSignal-Xamarin-SDK#314]
**Description:**

When calling "OneSignal.Default.SetExternalUserId("3483843204") we get below error
![image](https://user-images.githubusercontent.com/16970109/177122819-bfbe6125-023b-4e06-bbe0-a1799bcace58.png)

Can you please advise, the error only gives us this

System.ArgumentNullException
  Message=Value cannot be null.
Parameter name: hashToken

I am using 
OneSignal  4.00
Xamarin forms  :5.0.0.2337

We are pretty much stuck here, any advise.

Many thanks for your prompt reply

**Comment by Dipannita20** [comment]
@tanaynigam @jkasten2  any update on this, I am also stuck here after migrating to 4.0.0. Please respond

**Comment by ChrisMonson** [comment]
It looks like this has been reported as fixed in v4.1.1, but it appears that this is still happening after updating. The only SetExternalUserId method that is available is the one with the optional authHash parameter, and calling OneSignal.Default.SetExternalUserId("12345") still results in the same error that was previously reported.

I've included a decompiled copy of the OneSignalSDKInternal class in v4.1.1 showing no overload of SetExternalUserId without the optional authHash parameter that was included in the fix for this. Not sure what happened here, but unfortunately it still seems to be broken for me.

[OneSignal.Xamarin.Core.OneSignalSDKInternal.txt](https://github.com/OneSignal/OneSignal-Xamarin-SDK/files/9106528/OneSignal.Xamarin.Core.OneSignalSDKInternal.txt)

**Comment by jkasten2** [comment]
The fixed ended up not making it into the 4.1.1 release, this is now included in the [4.1.2 release](https://github.com/OneSignal/OneSignal-Xamarin-SDK/releases/tag/4.1.2).
