### ISSUE TITLE
How to get additionalData when App is closed?

### ISSUE THREAD

**Issue by glat** [OneSignal/OneSignal-Xamarin-SDK#42]
I noticed that in this case:

1. launchUrl empty
2. notificationOpenedDelegate used
3. App is fully closed

when the App gets a notification first the delegate is called and later the App is started causing the impossibility to get any data about the notification.

I checked android sdk source code and I think that in this function:
public static void handleNotificationOpen(Context inContext, JSONArray data, boolean fromAlert)
runNotificationOpenedCallback and latest if should be inverted, so to start App before to callback.
Android SDK maintainer told me that it is the correct order.

My aim is to get an ID by additionalData, and AFTER the app is started, use it to get data in db to show data to the user. Actually I get additionalData correctly, but later the App is restarted and it loose any data got before.

**Comment by Nightsd01** [comment]
It appears this issue has been resolved as I am unable to reproduce it. 

As long as you put `content_available` = 1 in your push notification, the handleNotificationReceived callback will get called. I was able to check and make sure that the `additionalData` field shows up just fine.

I am assuming that, since I cannot reproduce your problem, you may have not been setting `content_available` in the push notification, or it may have been an old bug that has been fixed. If you are still encountering this issue please feel free to respond and I'll be happy to reopen and investigate.
