### ISSUE TITLE
Does OneSignal-Xamarin-SDK support NetStandard?

### ISSUE THREAD

**Issue by satputerohan** [OneSignal/OneSignal-Xamarin-SDK#56]

**Comment by EmilAlipiev** [comment]
It seems like no. i just converted my pcl project to .net standard and it show yellow icon. did you try it?

**Comment by satputerohan** [comment]
It doesn't yet.

**Comment by gviddy** [comment]
This is important as all new Xamarin Apps built with VS 2017 only use NetStandard and no longer portable libraries... As such I cannot use this library currently until it is upgraded to NetStandard....

**Comment by EmilAlipiev** [comment]
I havent tried yet because of rollback to PCL but I guess that it still works on a net standard project. please share your experience if it works or not for you

**Comment by gviddy** [comment]
oh it seems to compile ok.. The package under the Nuget folder has a yellow triangle and the following warning appears when you compile but it all seems to work ok and I am receiving notifications....

warning NU1701: Package 'Com.OneSignal 3.0.1' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETStandard,Version=v2.0'. This package may not be fully compatible with your project.

**Comment by tidusjar** [comment]
I am also having the same issue, can we please get .Net Standard support for this library. 

Currently I am not able to use it.

**Comment by EmilAlipiev** [comment]
you can use it having it like below in your csproj file. This ensures that any package doesnt support net standard has compatibility with PCL versions

```
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <PackageTargetFallback>$(PackageTargetFallback);portable-win+net45+wp8+win81+wpa8</PackageTargetFallback>
  </PropertyGroup>
```

**Comment by jkasten2** [comment]
Apologize for the lack updates, we'll be releasing an update this coming month to address this issue and others. Created issue #62 with more details. Thanks

**Comment by jkasten2** [comment]
We just published a [3.1.0 beta release](https://github.com/OneSignal/OneSignal-Xamarin-SDK/releases/tag/3.1.0-beta) that now supports .NET Standard projects. Please try it out and let us know if there are any issues.

**Comment by EmilAlipiev** [comment]
i cant install on my net standard 2.0 project. "Com.OneSignal 3.1.0 is not compatible with netstandard2.0"

**Comment by jkasten2** [comment]
@EmilAlipiev Thanks for reporting!, looks like .NET Support broke from the 3.1.0-beta to the 3.1.0 release. We rebuilt and repacked the SDK which solved the issue and pushed a new version of 3.1.1 to NuGet. It should show up within the next hour or 2.

**Comment by jkasten2** [comment]
@EmilAlipiev Looks like this got missed when we switched the `.nuspec` to .NET Standard. Opened issue #79 to track this.

**Comment by tidusjar** [comment]
I don't know much about the company/group, but is there a QA process for these things?

**Comment by jkasten2** [comment]
@tidusjar The core native libraries ([OneSignal-Android-SDK](https://github.com/OneSignal/OneSignal-Android-SDK) & [OneSignal-iOS-SDK](https://github.com/OneSignal/OneSignal-iOS-SDK)) used by this Xamarin repo are well tested and includes a number of unit tests with good test coverage.
* [Travis-CI OneSignal-Android-SDK](https://travis-ci.org/OneSignal/OneSignal-Android-SDK)
* [Travis-CI OneSignal-iOS-SDK](https://travis-ci.org/OneSignal/OneSignal-iOS-SDK)

Most of our testing is done with the `OneSignal.sln` in the root of this repo. It's setup just includes project references to a sample project which is allows for faster development but different than a NuGet reference. We do do final manual testing with the `.nupkg` with new Visual Studio solutions of the Xamarin Forms and Native app type along with a PCL and .NET Standard project.

This 3.1.0 release included some large changes and restructuring to support .NET Standard and so we provided some beta and alpha releases on NuGet to test with. Due to the large scope of changes  things were as there was a build issue missing .NET Standard support and debug symbols in the final 3.1.0 release.

We are open to adding CI tests to this project as well. Simply adding some tests to build these projects types would prevent some of these configuration change related issues. A PR for this would  welcome, otherwise we can look into this at a later point as well.
